import PDFDocument from 'pdfkit';
import fs from 'fs';
import path from 'path';
import type { GapReport, CheckResult, ReadinessGap } from '../types';

const FONT_SIZE_TITLE = 20;
const FONT_SIZE_HEADING = 14;
const FONT_SIZE_BODY = 10;
const FONT_SIZE_SMALL = 8;
const MARGIN = 50;
const LINE_GAP = 4;

function addHeader(doc: PDFKit.PDFDocument, report: GapReport): void {
  const meta = report.metadata;
  doc
    .fontSize(FONT_SIZE_TITLE)
    .text('AgentLedger Compliance Readiness Assessment', MARGIN, MARGIN);

  doc
    .fontSize(FONT_SIZE_BODY)
    .moveDown(0.5)
    .text(`Regulation: ${meta.regulation} ${meta.article}`)
    .text(`Traces analyzed: ${meta.traceCount}  |  Format: ${meta.format}`)
    .text(`Date: ${meta.date.split('T')[0]}  |  Tool version: ${meta.toolVersion}`);

  if (meta.domain) {
    doc.text(`Domain: ${meta.domain}`);
  }

  doc
    .moveDown(0.5)
    .fontSize(FONT_SIZE_SMALL)
    .fillColor('#666666')
    .text(
      'NOTE: EU AI Act Article 12 applies to high-risk AI systems per Annex III. ' +
      'This scan evaluates trace data quality against Article 12 requirements. ' +
      'It is not a legal compliance determination.',
    )
    .fillColor('#000000')
    .moveDown(1);
}

function addScoreSummary(doc: PDFKit.PDFDocument, report: GapReport): void {
  const tq = report.score.traceQuality;
  const rd = report.score.readiness;
  const overall = report.score.overall.toUpperCase();

  doc
    .fontSize(FONT_SIZE_HEADING)
    .text('Summary', { underline: true })
    .moveDown(0.3);

  doc
    .fontSize(FONT_SIZE_BODY)
    .text(`Overall verdict: ${overall}`)
    .text(`Trace Quality: ${tq.passed}/${tq.total} checks passing (${tq.percentage}%)`)
    .text(`Readiness Gaps: ${rd.verified}/${rd.total} verified`)
    .moveDown(1);
}

function addTraceQuality(
  doc: PDFKit.PDFDocument,
  results: CheckResult[],
): void {
  doc
    .fontSize(FONT_SIZE_HEADING)
    .text('Trace Quality (verified from data)', { underline: true })
    .moveDown(0.3);

  for (const r of results) {
    const status = r.percentage >= 100 ? 'PASS' : r.percentage >= 50 ? 'WARN' : 'FAIL';
    const color = status === 'PASS' ? '#22c55e' : status === 'WARN' ? '#eab308' : '#ef4444';

    doc
      .fontSize(FONT_SIZE_BODY)
      .fillColor(color)
      .text(`[${status}]`, { continued: true })
      .fillColor('#000000')
      .text(
        `  ${r.check.id} — ${r.passed}/${r.total} (${r.percentage}%)  ` +
        `[${r.check.severity}]  Art. ${r.check.article}`,
      );

    if (r.percentage < 100) {
      doc
        .fontSize(FONT_SIZE_SMALL)
        .fillColor('#666666')
        .text(`      ${r.check.description.trim()}`, { indent: 10 })
        .fillColor('#000000');
    }
  }

  doc.moveDown(1);
}

function addReadinessGaps(
  doc: PDFKit.PDFDocument,
  gaps: ReadinessGap[],
): void {
  doc
    .fontSize(FONT_SIZE_HEADING)
    .text('Readiness Gaps (needs organizational verification)', { underline: true })
    .moveDown(0.3);

  for (const gap of gaps) {
    doc
      .fontSize(FONT_SIZE_BODY)
      .fillColor('#eab308')
      .text('[CHECK]', { continued: true })
      .fillColor('#000000')
      .text(
        `  ${gap.definition.id} — [${gap.definition.severity}]  Art. ${gap.definition.article}`,
      );

    doc
      .fontSize(FONT_SIZE_SMALL)
      .fillColor('#666666')
      .text(`      ${gap.definition.description.trim()}`, { indent: 10 })
      .text(`      Recommendation: ${gap.definition.recommendation.trim()}`, { indent: 10 })
      .fillColor('#000000')
      .moveDown(0.3);
  }

  doc.moveDown(1);
}

function addFooter(doc: PDFKit.PDFDocument, report: GapReport): void {
  doc
    .fontSize(FONT_SIZE_SMALL)
    .fillColor('#999999')
    .text(
      `Generated by AgentLedger Scanner v${report.metadata.toolVersion} — ` +
      'https://github.com/2434addy/AgentLedger',
      MARGIN,
      doc.page.height - MARGIN,
      { align: 'center' },
    )
    .fillColor('#000000');
}

export function renderPdf(
  report: GapReport,
  outputPath: string,
): Promise<string> {
  const resolvedPath = path.resolve(outputPath);

  return new Promise<string>((resolve, reject) => {
    const doc = new PDFDocument({
      size: 'A4',
      margins: { top: MARGIN, bottom: MARGIN + 20, left: MARGIN, right: MARGIN },
      info: {
        Title: 'AgentLedger Compliance Readiness Assessment',
        Author: 'AgentLedger Scanner',
        Subject: `${report.metadata.regulation} ${report.metadata.article}`,
      },
      bufferPages: true,
    });

    const stream = fs.createWriteStream(resolvedPath);
    stream.on('finish', () => resolve(resolvedPath));
    stream.on('error', reject);
    doc.pipe(stream);

    addHeader(doc, report);
    addScoreSummary(doc, report);
    addTraceQuality(doc, report.traceQuality);
    addReadinessGaps(doc, report.readinessGaps);
    addFooter(doc, report);

    doc.end();
  });
}
